spring:
  profiles:
    active:
      - cat
      - EN
      - prod
guru:
  username: YmlUserName
  password: YmlPass
  jdbcurl: YmlUrl

---
spring:
  profiles: prod
guru:
  username: YmlProdUserName
  password: YmlProdPass
  jdbcurl: YmlProdUrl